language: c
dist: bionic
matrix:
  include:
    - compiler: gcc
      env: BUILD=cmake

before_install:
  - sudo apt update
install:
  - sudo apt install -y cpputest
script:
  - cmake . -DCOMPILE_TESTS=ON -DCPPUTEST_HOME=/usr -DCOVERAGE=ON
  - make
  - make test
  - gcov src/libATtiny861/*.c
