#ifndef ATTINY861_RETURN_CODES_INCLUDED
#define ATTINY861_RETURN_CODES_INCLUDED

typedef enum
{
    ATTINY861_SUCCESS       = 0,
    ATTINY861_NULL_POINTER  = -1,
    ATTINY861_INVALID_PIN  	= -2,
    ATTINY861_INVALID_STATE = -3,
} ATTINY861_RETURN_CODE;

#endif
