#ifndef ATTINY861_RETURN_CODES_INCLUDED
#define ATTINY861_RETURN_CODES_INCLUDED

typedef enum
{
    ATTINY861_SUCCESS       = 0,
    ATTINY861_NULL_POINTER  = -1,
    ATTINY861_GPIO_INVALID  = -2,
    ATTINY861_STATE_INVALID = -3,
} ATTINY861_STATUS_CODE;

#endif
